//ALL CONSTANTS
const SUITS = {
  HEARTS: 'HEARTS',
  SPADES: 'SPADES',
  CLUBS: 'CLUBS',
  DIAMONDS: 'DIAMONDS',
}

const GAME_STATES = {
  INIT_PLAYERS: 'INIT_PLAYERS',
  INIT_GAME: 'INIT_GAME',
  GAME_END: 'GAME_END',
}

//order matters here
const ORDERED_CARD_SUIT = [
  SUITS.DIAMONDS,
  SUITS.CLUBS,
  SUITS.HEARTS,
  SUITS.SPADES,
]

const MIN_CARD_VALUE = 1
const MAX_CARD_VALUE = 13
